development:
  clients:
    default:
      database: testing
      hosts:
        - 10.255.8.148:27017
    nauth:
      database: nauth
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: htgd
      hosts:
        - 10.255.8.148:27017
    nauth:
      database: nauth
      hosts:
        - localhost:27017
     
